improve node management
samchon/nestia pull request #1153
Opened 2024-12-13 09:54 UTC by ryoppippi

- manage pnpm version by pnpm
- manage node version by ci
- install node & pnpm using pnpm itself in ci env
-

2024-12-13 10:48 UTC, samchon reviewed
I think `nestia` needs matrix strategy of NodeJS versions. Others are good to see.

2024-12-13 10:50 UTC, samchon requested changes
Also, ignoring `pnpm-lock.yaml` file is inteded.

As this is a library repository, I've always test the `^` version setup startegy.

2024-12-13 16:34 UTC, ryoppippi commented
OK, then use another pr!

2024-12-13 16:40 UTC, ryoppippi commented
I'll add matrix later

2024-12-13 16:41 UTC, ryoppippi commented
So managing node version by pnpm is not good for this case?

2024-12-14 17:34 UTC, samchon requested changes
As `nestia` utilizes many NodeJS built-in functions, I think NodeJS version matrix is valid for this repo.

Also, do not change too much style please. Ignoring `pnpm-lock.yaml` file is required for dependencies' patch and minor updates.

2024-12-14 17:40 UTC, samchon commented on .github/workflows/website.yml
Also, website must use `npm` at now.

This may be caused by my unskilled monorepo composition, anyway, if try to use `pnpm install` command in the `website` directory, it does not install of `website`, but of other modules enrolled in the `pnpm-workspace.yaml` file.

By the way, if add the `website` directory to the `pnpm-workspace.yaml` file is impossible. It is because the `website` module requires other module's complete compilation and testing.

2024-12-14 17:44 UTC, samchon requested changes
Thanks for your endless contribution.

There may be a better and more superior solution, or I may have made a wrong choice.

However, the changes must be made at a level that I can keep going the development.

2024-12-14 17:44 UTC, samchon commented on pnpm-lock.yaml
This must be removed with below commented reason.

2024-12-14 17:44 UTC, samchon commented on .gitignore
Also change please

2024-12-14 17:44 UTC, samchon commented on .github/workflows/website.yml
> -        run: npm install && npm run build
Also, website must use `npm` at now.

This may be caused by my unskilled monorepo composition, anyway, if try to use `pnpm install` command in the `website` directory, it does not install of `website`, but of other modules enrolled in the `pnpm-workspace.yaml` file.

By the way, if add the `website` directory to the `pnpm-workspace.yaml` file is impossible. It is because the `website` module requires other module's complete compilation and testing.

2024-12-31 01:45 UTC, ryoppippi commented
I'll create another PR based on this!

2024-12-31 01:45 UTC, closed without merging