Fix NestiaConfigLoader causing error with tsconfig compilerOption `react`
samchon/nestia pull request #968
Opened 2024-07-24 08:48 UTC by p-sw

Here is the issue: #966 

## Reason
1. `nestia sdk` internally uses NestiaConfigLoader
2. NestiaConfigLoader's which uses `tsconfck.parseNative` to parse compilerOption from tsconfig (reference [here](https://github.com/samchon/nestia/blob/master/packages/sdk/src/executable/internal/NestiaConfigLoader.ts#L20))
3. `tsconfck.parseNative` uses typescript's native function, `readConfigFile` and `parseJsonConfigFileContent`
4. `parseJsonConfigFileContent` causes error - it resolves `jsx` to `number`, but `jsx` should be string!
5. ERROR

2024-07-24 10:20 UTC, p-sw commented
It seems like the test is failing because of working directory.

I run `npm run test` on the root directory, it works fine without any error.

But If I `cd test` and then `npm run test`, it cause the error same as action.

I'm not sure why...

2024-07-25 10:53 UTC, samchon commented
@p-sw The test program is running the `npx nestia sdk` or `npx nestia swagger` command in each directory by configuring specific `cwd (current working directory)`.

2024-07-25 11:05 UTC, samchon requested changes
@p-sw The test program is running the `npx nestia sdk` or `npx nestia swagger` command in each directory by configuring specific `cwd (current working directory)`.

The bug has come from bumping up the `tsconfck` dependency, which does not support CJS program.

2024-07-25 11:05 UTC, samchon reviewed
Rolling back the `tsconfck` version will make your PR work.

2024-07-25 16:46 UTC, merged